### ISSUE TITLE
calcolo del tempo

### ISSUE THREAD

**Issue by FabioZTessitore** [tonyiovino/endurance#2]
il calcolo del tempo va modificato. Vogliamo ore minuti e secondi

**Comment by tonyiovino** [comment]
Mh... Fammici pensare... Con quella formuletta ( "%" e "/" ) ?

**Comment by FabioZTessitore** [comment]
non mi hai aggiunto come collaboratore

**Comment by FabioZTessitore** [comment]
Si

Il gio 30 mag 2019, 23:04 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Prima che risolva quest'algoritmo, vorrei specificare una cosa: non ricordo di presunte "q_str".
Se me le aveste spiegate, chedo cortesemente di accendere un lumino nella mia testa... :-)

**Comment by FabioZTessitore** [comment]
È solo un nome di variabile

Il ven 31 mag 2019, 18:36 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Che mi serve a... ?

**Comment by FabioZTessitore** [comment]
Probabilmente è un valore letto in input.

Il ven 31 mag 2019, 18:40 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Ovviamente... hahahahaha

**Comment by tonyiovino** [comment]
Calcolo il numero in ore con la formula (quantita / conusmo orario), poi dovrei fare il resto di 60 per ognuno?
Non penso...

**Comment by FabioZTessitore** [comment]
Il resto, punto. Devi solo capire cosa esce e se c'è bisogno di altri
calcoli

Il ven 31 mag 2019, 19:12 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
Il resto dovrei moltiplicarlo per 60. Giusto?

**Comment by FabioZTessitore** [comment]
Si. Ma non è finita

Il ven 31 mag 2019, 19:26 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
ripetere il processo fino a secondi?

**Comment by FabioZTessitore** [comment]
Si

Il ven 31 mag 2019, 19:38 tonyiovino <notifications@github.com> ha scritto:

**Comment by tonyiovino** [comment]
E come faccio a far rimanere le ore e non far "mischiare" con altri numeri?

**Comment by FabioZTessitore** [comment]
non ci siamo ancora

**Comment by FabioZTessitore** [comment]
non so se ci sei arrivato o sei hai guardato la soluzione, ma in ogni caso è chiaro come risolvere il problema?
ps. proviamo a dare alle variabili dei nomi comprensibili e ad utilizzare solo quelle che servono realmente

**Comment by tonyiovino** [comment]
Non ho guardato la soluzione, mi sono fatto aiutare a capire come risolvere il problema fecendogli vedere la soluzione. Il prof di laboratorio Cutolo Giovanni.

**Comment by tonyiovino** [comment]
Ero nel laboratorio al 2° piano, di mercoledì, il vostro giorno libero, ed ero l'unico della mia classe ad essere stato presente, quindi ho deciso di avere comunque una giornata produttiva! :-)

**Comment by tonyiovino** [comment]
...tranne in italiano.

**Comment by FabioZTessitore** [comment]
ora però cerca di riorganizzare quelle righe, usa solo le variabili che servono e metti nomi significativi

**Comment by tonyiovino** [comment]
Okay

Il Ven 7 Giu 2019 20:50 Fabio Z Tessitore <notifications@github.com> ha
scritto:
